/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.
 */

// @ts-check

/** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */
const sidebars_stack = {
  '👀 CV': [
    {
      // type: 'autogenerated',
      // dirName: '.'
      type: 'category',
      label: '👀 Perception',
      link: {
        type: 'generated-index',
        slug: '/category/perception',
      },
      collapsed: true,
      items: [
        {
          type: 'category',
          label: 'OpenCV',
          link: {
            type: 'generated-index',
            slug: '/category/OpenCV',
          },
          collapsed: true,
          items: [
            'cv/perception/opencv/opencv-install',
          ],
        },

      ]
    }
  ],
};

export default sidebars_stack;
