/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.
 */

// @ts-check

/** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */
const sidebars_stack = {
  '👀 CV': [
    {
      // type: 'autogenerated',
      // dirName: '.'
      type: 'category',
      label: '👀 Perception',
      link: {
        type: 'generated-index',
        slug: '/category/perception',
      },
      collapsed: true,
      items: [
        {
          type: 'category',
          label: 'OpenCV',
          link: {
            type: 'generated-index',
            slug: '/category/OpenCV',
          },
          collapsed: true,
          items: [
            'cv/perception/opencv/opencv-install',
          ],
        },

      ]
    }
  ],

  '🤖 Robot': [
    {
      // type: 'autogenerated',
      // dirName: '.'
      type: 'category',
      label: '🛴 Motion Control',
      link: {
        type: 'generated-index',
        slug: '/category/control',
      },
      collapsed: true,
      items: [
        {
          type: 'category',
          label: 'PID',
          link: {
            type: 'generated-index',
            slug: '/category/PID',
          },
          collapsed: true,
          items: [
            'robot/control/pid/classic-pid',
            'robot/control/pid/classic-pid-optimization',
          ],
        },

      ]
    },
    {
      // type: 'autogenerated',
      // dirName: '.'
      type: 'category',
      label: '🏁 Path Planning',
      link: {
        type: 'generated-index',
        slug: '/category/planning',
      },
      collapsed: true,
      items: [
        {
          type: 'category',
          label: 'grid_search',
          link: {
            type: 'generated-index',
            slug: '/category/grid_search',
          },
          collapsed: true,
          items: [
            'robot/path_planning/grid_search/path_planning_grid_map',
            'robot/path_planning/grid_search/path_planning_astar',
            'robot/path_planning/grid_search/path_planning_jps',
            'robot/path_planning/grid_search/path_planning_astar_optimize',
          ],
        },

      ]
    }
  ],

  '⌨️ Software': [
    // C/C++
    {
      type: 'category',
      label: 'C/C++',
      link: {
        type: 'generated-index',
        slug: '/category/cpp',
      },
      collapsed: true,
      items: [
        'software/cpp/cpp-pointers-reference',
        {
          type: "category",
          label: "OOP",
          collapsed: true,
          items: [
            'software/cpp/oop/cc-classes-and-objects',
            'software/cpp/oop/cc-classes-inheritance',
            'software/cpp/oop/cc-classes-virtual-function',
          ],
        },
        {
          type: "category",
          label: "STL",
          collapsed: true,
          items: [
            'software/cpp/stl/cc-stl-frame',
            'software/cpp/stl/cc-stl-containers',
          ],
        },
      ]
    },
    // Algorithm
    {
      type: 'category',
      label: 'Algorithm',
      link: {
        type: 'generated-index',
        slug: '/category/algorithm',
      },
      collapsed: true,
      items: [
        {
          type: "category",
          label: "🗄️ Stack",
          collapsed: true,
          items: [
            'software/algorithm/stack/algorithm-hard-85-maximal-rectangle',
          ],
        },
        {
          type: "category",
          label: "🌲 Tree",
          link: {
            type: 'generated-index',
            slug: '/category/tree',
          },
          items: [
            'software/algorithm/tree/data-structures-tree-traversal',
            'software/algorithm/tree/data-structures-tree-level-order',
            'software/algorithm/tree/data-structures-tree-depth',
          ],
        },
        {
          type: "category",
          label: "🍩 Greedy",
          collapsed: true,
          items: [
            'software/algorithm/greedy/algorithm-376-wiggle-subsequence',
            'software/algorithm/dp/algorithm-53-max-sub-array',
            'software/algorithm/dp/algorithm-122-best-time-to-buy-and-sell-stock-ii',
          ],
        },
        {
          type: "category",
          label: "🗂 DP",
          collapsed: true,
          items: [
            'software/algorithm/greedy/algorithm-376-wiggle-subsequence',
            'software/algorithm/dp/algorithm-122-best-time-to-buy-and-sell-stock-ii',
            'software/algorithm/dp/algorithm-53-max-sub-array',
          ],
        },
      ]
    },
    // design-pattern
    {
      type: 'category',
      label: 'design-pattern',
      link: {
        type: 'generated-index',
        slug: '/category/design-pattern',
      },
      collapsed: true,
      items: [
        'software/design-pattern/design-pattern-gof',
        'software/design-pattern/design-pattern-singleton',
        'software/design-pattern/design-pattern-abstract-factory',
      ]
    },
  ],
};

export default sidebars_stack;
